print('Welcome to food frensy!')
print('1. Hamburger')
print('2. Pizza')
print('3. Taco')
print('4. Cookie')
print('5. Milk')
print('6. Exit')
food = input('Select an item to order: ')
print('You ordered: ' + food + '.')
if food = 1 print('hamburger')
